# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
sudo: false
cache: packages
latex: true
pandoc_version: 2.5
before_install:
  - R -q -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")'
  - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl", quietly = TRUE)) install.packages("curl")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic@bookdown"); tic::prepare_all_stages()'

script: true
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true

